/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/pages/**/*.{js,ts,jsx,tsx}', './src/components/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    'text-purple_dark',
    'text-green_dark',
    'text-red_dark',
    'text-blue_dark',
    'text-black_dark',
    'text-steel_dark',
    'text-rock_dark',
    'text-sand_dark',
    'bg-purple',
    'bg-green',
    'bg-red',
    'bg-blue',
    'bg-black',
    'bg-steel',
    'bg-rock',
    'bg-sand',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#272E4D',
        primary_light: '#313961',
        primary_light2: '#333C63',
        primary_light3: '#A6B1E1',
        primary_light4: '#CFD8FF',
        secondary: '#FFD76F',
        green: '#06A157',
        green_light: '#09AA5C',
        green_dark: '#077C44',
        red: '#9D2F2F',
        red_light: '#C14444',
        red_dark: '#692020',
        yellow: '#DCAF02',
        yellow_light: '#FFCB05',
        yellow_dark: '#997900',
        blue: '#028DDC',
        blue_light: '#05A5FF',
        blue_dark: '#006096',
        purple: '#6D2F9D',
        purple_light: '#9240C5',
        purple_dark: '#4D2069',
        steel: '#CAD7E1',
        steel_light: '#B5C0C9',
        steel_dark: '#7B8389',
        rock: '#D4C3D9',
        rock_light: '#8A7F8D',
        rock_dark: '#665C68',
        black: '#222',
        black_light: '#333',
        black_dark: '#111',
        sand: '#EBD8C8',
        sand_light: '#DECDBE',
        sand_dark: '#C3B3A4',
      },
    },
  },
  plugins: [],
}
